root: true

parser: '@typescript-eslint/parser'

env:
  jest: true
  node: true

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint-config-airbnb-base'

parserOptions:
  ecmaVersion: 2019
  sourceType: module

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts

rules:
  linebreak-style:
    - 0
  '@typescript-eslint/no-use-before-define':
    - 0
  no-use-before-define:
    - 0
  '@typescript-eslint/array-type':
    - 0
  '@typescript-eslint/ban-ts-ignore':
    - 0
  '@typescript-eslint/camelcase':
    - 0
  '@typescript-eslint/indent':
    - 2
    - 2
  '@typescript-eslint/no-explicit-any':
    - 0
  '@typescript-eslint/no-non-null-assertion':
    - 0
  '@typescript-eslint/no-unused-vars':
    - 2
    - argsIgnorePattern: "^_"
  camelcase:
    - 0
  class-methods-use-this:
    - 0
  consistent-return:
    - 0
  function-paren-newline:
    - 0
  implicit-arrow-linebreak:
    - 0
  import/extensions:
    - 0
  import/no-extraneous-dependencies:
    - 2
    - devDependencies:
      - "**/*.test.ts"
      - "src/bin/*.ts"
      - "src/lib/jest/*.ts"
  max-classes-per-file:
    - 0
  max-len:
    - 2
    - ignoreComments: true
      ignorePattern: "^import"
      code: 120
  newline-per-chained-call:
    - 0
  no-await-in-loop:
    - 0
  no-bitwise:
    - 0
  no-confusing-arrow:
    - 0
  no-param-reassign:
    - 0
  no-restricted-syntax:
    - 0
  no-return-assign:
    - 0
  no-shadow:
    - 0
  no-underscore-dangle:
    - 0
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
  object-curly-newline:
    - 0
  quote-props:
    - 0
